### PR TITLE
Updates for 2.18.0.0

### PR DESCRIPTION
**Pull request by riddell-stan**

### CODE REVIEW

**Comment by riddell-stan** [comment]
- Python 3.7 is failing on Linux, hard to see exactly why in the build logs
- macOS is failing, looks like the version of clang used is unhappy with something. PyStan tests against clang on linux (likely a different version of clang).

Everything else works.

**Comment by ahartikainen** [comment]
Could we add verbosity for osx build (by adding `set -x` somewhere in travis file).

There is some problem with ssl in one of  the jobs. (osx)

Could osx problem be with `libc++` vs `libstdc++`?

**Comment by ahartikainen** [comment]
I created one build with verbose tag

https://travis-ci.org/ahartikainen/pystan-wheels/jobs/419357328

osx default std namespace is missing some functions for C++11

So we need `-stdlib=libc++` for osx people (will test this)

https://svn.boost.org/trac10/ticket/8092

**Comment by riddell-stan** [comment]
Thanks so much for getting to this. I've been swamped with the start of 
the academic year.

**Comment by ahartikainen** [comment]
Hi, I tested it and it appears that the toolchain is too old and does not support C++11? Can we update the toolchain on osx?

```
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```
https://travis-ci.org/ahartikainen/pystan-wheels/jobs/419523441

Also, is the openssl too old so pip is failing to download pbr for py3x.

```
Download error on https://pypi.org/simple/pbr/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    No local packages or working download links found for pbr
```

Finally py37 is failing on its own (building wheel).

**Comment by riddell-stan** [comment]
Let's deal with the 3.7 and the macOS problems separately. macOS is the priority.

So what should we do? If we're going to require a certain version of macOS / Xcode, we need to add that to the documentation in pystan proper.

Would using xcode 10 solve the problem? travis says we can add ``osx_image: xcode10`` to the ``.travis.yml``.

**Comment by ahartikainen** [comment]
Hmm, apparently Apple has its own method of versioning clang.

    Apple LLVM version 9.1.0 (clang-902.0.39.2)

Which equals some unknown llvm version.

So I'm not even sure if the `libc++` is the correct thing to do. It should exist and should be used automatically.

What RStan or CmdStan did? They should have had the same problems?

**Comment by riddell-stan** [comment]
@ahartikainen I take it you don't have a mac? Should we perhaps ask one of the other Stan devs who has a mac to take a look at this? If all we have to do is restrict the versions of Xcode we support, I'm more than happy to do that. (I don't want to have to add special flags for macOS in PyStan.)

**Comment by ahartikainen** [comment]
I have one, but it is currently not in use.

But I think we can officially support C++11 enabled xcode and then let advanced users to install newer compiler with brew.

**Comment by ahartikainen** [comment]
Ok, I try to run with my laptop to see what is the problem.

**Comment by ahartikainen** [comment]
Yeah, so... Everything works as planned.
```
OSX El Capitan 
10.11.6 (15G20015)

clang --version
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: 
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```


I have Xcode 8 toolchain on , I cloned the pystan repo and did `pip install -e .`. Version 2.18.

Compiling PyStan works, compiling stan models works, sampling works, tests are working. 

There must be something wrong how Travis is setting up the toolchain. Are we running the tests in the main folder?

Good thing is that we don't need to tell users to install a specific version of Xcode.

**Comment by riddell-stan** [comment]
Nothing changed in this repository between 2.17 and 2.18 -- just the PyStan code. (macOS wheels were built fine for 2.17.) So I suspect it's not a simple travis problem.

I'll try one thing to help with debugging now.

(also, as a side note, let's just forget about Python 3.7 for now, we can do that for the next release.)

**Comment by ahartikainen** [comment]
We could `pip install pbr` manually. There are some problems with it if installed from some `requirements` file.

The error has something to do with `C++11`: `fatal error: 'type_traits' file not found`

e.g. https://github.com/openMVG/openMVG/issues/316

We could move to gcc toolchain (atleast until we figure out what is going on)?

https://docs.travis-ci.com/user/languages/cpp/

https://docs.travis-ci.com/user/languages/cpp/#c11c11-and-beyond-and-toolchain-versioning

here is an example:

https://docs.travis-ci.com/user/languages/cpp/#gcc-on-os-x

```
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
```

**Comment by riddell-stan** [comment]
re: switching to gcc, I'm keen to reduce our maintenance burden here. I'd like to stick to the defaults that ``multibuild`` provides/supports. (In fact, I'd like to move the Windows wheel-building over to pystan-wheels too.)

Looks like there's a C++11/14 issue. Surely this can be fixed.

**Comment by riddell-stan** [comment]
Are we just missing ``-stdlib=libc++``? Adding that will not break gcc, right?

**Comment by riddell-stan** [comment]
We might also need/want to set ``MACOSX_DEPLOYMENT_TARGET=10.9`` (see https://github.com/matthew-brett/multibuild/issues/188 )

**Comment by ahartikainen** [comment]
`-stdlib=libc++` could break stuff with gcc.

I think using only multibuild is a good idea.

**Comment by ahartikainen** [comment]
I think `MACOSX_DEPLOYMENT_TARGET=10.7` could be enough. 

My guess is that we don't need to set stdlib, it is set automatically.

**Comment by riddell-stan** [comment]
Looks like ``MACOSX_DEPLOYMENT_TARGET=10.9`` might be required:

https://stackoverflow.com/questions/23666754/default-to-lib-stdlibc-for-clang-on-mac-os-mavericks-with-xcode

**Comment by ahartikainen** [comment]
To test gcc one has to reset CC and CXX flags after multibuild has set them to clang.

**Comment by riddell-stan** [comment]
I'm going to try one more time with clang. I'm optimistic. Otherwise we 
need to figure out some way to manually set the stdlib to libc++ .

**Comment by ahartikainen** [comment]
Could this be related?

https://github.com/mono/mono/issues/9227

Because we have these warnings:
```
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
```

https://travis-ci.org/ahartikainen/pystan-wheels/jobs/421031578

**Comment by ahartikainen** [comment]
That did work. 

For py35 it needs `pip install pbr` somewhere before it tries to install it as dependency. (maybe after pip is updated).

py37 is failing with timeout. So is this some travis bug?

**Pull request merged**
