### PR TITLE
fix: updates for Stan 2.19, many changes

### PR DESCRIPTION
**Pull request by riddell-stan**
- Use a custom manylinux image which has a newer version of gcc.
- Use a custom text runner image (riddellstan/xenial) instead of
matthewbrett/trusty, again for a newer version of gcc.

### CODE REVIEW

**Comment by riddell-stan** [comment]
This is weird. Builds wheel successfully but wheel is corrupt?

```
Successfully built pystan
warning [/io/wheelhouse/pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl]:  76 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [/io/wheelhouse/pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl]:  reported length of central directory is
  -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
error:  expected central file header signature not found (file #67320).
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
Repairing pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl
```

**Comment by ahartikainen** [comment]
Is there some problem with wheel?

https://pypi.org/project/wheel/#history

Maybe first try with 0.32.3

**Comment by riddell-stan** [comment]
It worked yesterday with httpstan-wheels. The configuration is (or 
should be) identical.

I'll double check everything later today.

**Comment by ahartikainen** [comment]
Could this be some interaction with old Numpy + gcc 8 + cython? (Numpy wheels are build; no prebuilt wheels for those versions)

**Comment by riddell-stan** [comment]
I'm able to reproduce this on my own machine (using a manylinux docker image). Very strange that it works fine with `httpstan-wheels`, https://travis-ci.org/stan-dev/httpstan-wheels/jobs/514444057. I wonder if it's some size issue. The wheel is very large.

**Comment by ahartikainen** [comment]
how large? Why is that wheel large?

**Comment by riddell-stan** [comment]
Actually, I'm not sure it's that much bigger. I figured it would be larger since now we have to compile with ``--static-libc++`` in order to be compatible with the manylinux1 standard.

I still don't understand why everything works with httpstan and things fail with pystan. They're both using Stan 2.19.

**Comment by riddell-stan** [comment]
If we can't build a manylinux1 wheel then we can't build it. With luck osx and windows wheels will be fine. And conda too.

**Comment by riddell-stan** [comment]
Found the problem: The wheel contains 73,451 files and the unzip used by manylinux1 (5.52) does not support the Zip64 format, so it is limited to 65,535 (2^16) files.

**Comment by ahartikainen** [comment]
Can we remove non-needed libs?

**Comment by ahartikainen** [comment]
Now linux works, but there is some problem with osx + py3k?

**Pull request merged**
